"""empty message

Revision ID: 4f8816e2b136
Revises: 1216c9ca5ee8
Create Date: 2023-12-07 20:14:53.232628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f8816e2b136'
down_revision: Union[str, None] = '1216c9ca5ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('keywords', sa.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'keywords')
    # ### end Alembic commands ###
